site_name: "Introducció a Git i la seua aplicació a l’aula"
site_author: "Joan Puigcerver Ibáñez"
site_email: "j.puigcerveribanez@edu.gva.es"
site_url: https://joapuiib.github.io/curs-git/
dev_addr: 127.0.0.1:4567

repo_name: joapuiib/curs-git
repo_url: https://github.com/joapuiib/curs-git

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joapuiib
      name: joapuiib a GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joanpuigcerver/
      name: Joan Puigcerver a LinkedIn

draft_docs: |
  *_unpublished.md
  *_draft.md

exclude_docs: |
  *_excluded.md
  _*

theme:
  name: material-joapuiib
  icon:
    logo: simple/git

  comments:
    data_repo: joapuiib/curs-git
    data_repo_id: R_kgDOMi7ohg
    data_category: General
    data_category_id: DIC_kwDOMi7ohs4Ch1Lw

  # cover: 
  #   logo: false

  # Palette toggle for light mode
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: 'deep orange'
      scheme: default
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-sunny
        name: Canvia a mode fosc

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: 'deep orange'
      scheme: slate
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-night
        name: Canvia a mode clar

plugins:
  - alias
  - awesome-pages # Navegació
  - drawio_file
  - macros
  - material/tags
  - material/search
  - material-joapuiib/enviorment
  - sectionicons
  - i18n:
      languages:
        - locale: ca
          default: true
          name: Valencià
          admonition_translations:
            note: Nota
            abstract: Resum
            tip: Consell
            success: Èxit
            question: Pregunta
            warning: Advertència
            failure: Error
            danger: Perill
            example: Exemple
            quote: Cita
            docs: Documentació
            solution: Solució
            important: Important
            notice: Fixa't
            prep: Preparació
  - git-revision-date-localized # Després de i18n o falla

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material_joapuiib.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.fancylists:
      inject_class: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 4
