name: build

on:
  push:
    branches:
      - 'main'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  documents:
    runs-on: ubuntu-latest
    env:
      DICPATH: .hunspell/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install dependencies
        run: pip install -U -r requirements.txt
      - name: Install pyspelling
        run: pip install pyspelling
      - name: Install hunspell
        run: |
          sudo apt update
          sudo apt install hunspell -y
      - name: Build documents
        run: mkdocs build --clean

      - name: Set up dictionary cache
        id: cache-file
      - name: Download dictionary
        run: |
          mkdir -p .hunspell
          curl -L https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/refs/heads/master/resultats/hunspell/catalan-valencia.dic -o .hunspell/ca_ES_valencia.dic
          curl -L https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/refs/heads/master/resultats/hunspell/catalan-valencia.aff -o .hunspell/ca_ES_valencia.aff
          hunspell -D
      - name: Spell check
        run: pyspelling
